export const ACTION_TYPE = {
    SET_USER: 'SET_USER',
    LOGOUT: 'LOGOUT',
    SEARCH_PRODUCT: 'SEARCH_PRODUCT',
    SET_CATEGORIES: 'SET_CATEGORIES',
    LOAD_PRODUCTS: 'LOAD_PRODUCTS',
    SELECT_PRODUCT: 'SELECT_PRODUCT',
    LOAD_CATEGORIES: 'LOAD_CATEGORIES',
    ADD_TO_CART: 'ADD_TO_CART',
    REMOVE_TO_CART: 'REMOVE_TO_CART',
    CLEAR_CART: 'CLEAR_CART',
    DECREMENT_FROM_CART: 'DECREMENT_FROM_CART',
    INCREMENT_FROM_CART: 'INCREMENT_FROM_CART',
    ADD_PRODUCT: 'ADD_PRODUCT',
    SELECTED_PRODUCT: 'SELECTED_PRODUCT'
}